server:
  port: 9000

spring:
  datasource:
    url: jdbc:h2:file:./oauth-authorization-server
    driver-class-name: org.h2.Driver
    username: h2
    password: h2
  h2:
    console:
      enabled: true
      path: /h2-console  # Console path
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
